version: '3.8'

services:
  app:
    build:
      context: .
    container_name: moonrabbit-app
    ports:
      - "3001:8080"
    env_file:
      - ./moonrabbit.env
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on: []
