name: Deploy to EC2 via Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. gradlew 권한 설정
      - name: Add execute permission to gradlew
        run: chmod +x gradlew

      # 4. Gradle Build (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5. Docker 로그인
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 6. Docker 이미지 빌드 & 푸시
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moonrabbit-backend-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/moonrabbit-backend-app:latest

      # 7. EC2 접속 키 저장
      - name: Save PEM key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # 8. EC2에 SSH 접속해서 컨테이너 업데이트
      - name: Connect to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "[1] Docker 로그인"
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

            echo "[2] 기존 컨테이너 중지 및 제거"
            docker stop moonrabbit-app || true
            docker rm moonrabbit-app || true

            echo "[3] 최신 이미지 Pull"
            docker pull $DOCKER_USERNAME/moonrabbit-backend-app:latest

            echo "[4] 컨테이너 재실행"
            echo "$MOONRABBIT_ENV" > .env
            docker run -d --name moonrabbit-app -p 8080:8080 --env-file .env $DOCKER_USERNAME/moonrabbit-backend-app:latest
          EOF
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          MOONRABBIT_ENV: ${{ secrets.MOONRABBIT_ENV }}
